from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi_pagination import add_pagination
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from app.database import Base, engine
from app.controllers import user_controller
from app.controllers import box_user_controller
from app.controllers import box_ai_api_model_controller
from app.auth.custom_router import router as custom_auth_router
# V-- 在这里自动引入新的控制器 --V


# 生命周期管理器，用于处理应用启动事件
@asynccontextmanager
async def lifespan(app: FastAPI):
    # 启动时创建模型中定义的所有数据表。
    # 生产环境如果使用 Alembic 管理迁移，可以移除这里。
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    # 这里可以放应用关闭时需要执行的代码


app = FastAPI(
    title="SKYBLUEAPI",
    description="A project generated by fast-boiler.",
    version="1.0.0",
    lifespan=lifespan
)

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    message = exc.detail if isinstance(exc.detail, str) else "error"
    return JSONResponse(status_code=200, content={"code": exc.status_code, "data": None, "message": message})


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(status_code=200, content={"code": 422, "data": exc.errors(), "message": "参数校验失败"})


# 跨域中间件
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# 注册业务资源路由
app.include_router(user_controller.router)
app.include_router(box_user_controller.router)
app.include_router(box_ai_api_model_controller.router)

# 注册认证相关路由
app.include_router(custom_auth_router, prefix="/auth", tags=["auth"])


# V-- 在这里自动注册新的路由 --V

add_pagination(app)


@app.get("/", tags=["Root"])
async def read_root():
    return {"code": 200, "data": {"message": "Welcome to the API!"}, "message": "success"}


