from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.database import Base, engine
from app.controllers import user_controller
from app.auth.routers import (
    auth_router,
    register_router,
    reset_password_router,
    users_router  # <-- NEW: Import the users_router
)
# V-- Auto-include new controllers here --V


# Lifespan manager to handle startup events
@asynccontextmanager
async def lifespan(app: FastAPI):
    # This creates all tables defined in your models on startup.
    # In a production app with Alembic, this would be removed.
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    # Code in this block would run on shutdown


app = FastAPI(
    title="SKYBLUEAPI",
    description="A project generated by fast-boiler.",
    version="1.0.0",
    lifespan=lifespan
)

# CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Include the main resource router (e.g., for users)
# This now provides the admin-only, paginated GET /users endpoint
app.include_router(user_controller.router)

# Include the authentication routers
app.include_router(auth_router, prefix="/auth/jwt", tags=["auth"])
app.include_router(register_router, prefix="/auth", tags=["auth"])
app.include_router(reset_password_router, prefix="/auth", tags=["auth"])

# 👇 NEW: Include the router for self-service and admin user management
app.include_router(users_router, prefix="/users", tags=["users"])


# V-- Auto-include new routers here --V


@app.get("/", tags=["Root"])
async def read_root():
    return {"message": "Welcome to the API!"}


